version:  2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    assignees:
      - "74C17N3P7UN3"
      - "mzyxnuel"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    assignees:
      - "mzyxnuel"
      - "TheInfernalNick"
    open-pull-requests-limit: 1
