version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    assignees:
      - "74C17N3P7UN3"
      - "mzyxnuel"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Rome"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/web"
    assignees:
      - "mzyxnuel"
      - "TheInfernalNick"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Rome"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1
